services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DB_NAME=taipei_attractions
      - REDIS_HOST=redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:  uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: